apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openshiftpulse
  namespace: {{ include "openshiftpulse.namespace" . }}
  labels:
    {{- include "openshiftpulse.labels" . | nindent 4 }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: openshiftpulse
  namespace: {{ include "openshiftpulse.namespace" . }}
  labels:
    {{- include "openshiftpulse.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshiftpulse:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: nginx:1.26-ubi9
